import type { BlogArticleMeta } from "./types";

export const blogArticles: BlogArticleMeta[] = [
  {
    id: "1",
    slug: "kak-pisat-poleznye-stati-v-aiffa",
    title: "Как писать полезные статьи в AIFFA",
    description:
      "Набор простых принципов: структура, примеры, практика, и как сделать материал ценным для сообщества.",
    date: "2025-12-10",
    tags: ["AIFFA", "Сообщество", "Контент"],
    author: { name: "n1ckwhite", github: "n1ckwhite" },
    viewsCount: 1320,
    starsCount: 48,
    commentsCount: 12,
    readingTime: "5 мин",
    coverImage:
      "/images/blog/1.webp",
    mdPath: "/articles/kak-pisat-poleznye-stati-v-aiffa.md",
  },
  {
    id: "2",
    slug: "git-pull-vs-fetch-na-praktike",
    title: "Git pull vs fetch — на практике и без мифов",
    description:
      "Разбираем, что реально происходит в репозитории, как читать историю, и какой командой пользоваться в разных ситуациях.",
    date: "2025-12-06",
    tags: ["Git", "Практика"],
    author: { name: "aiffadev", github: "aiffadev" },
    viewsCount: 980,
    starsCount: 32,
    commentsCount: 7,
    readingTime: "7 мин",
    coverImage:
      "/images/blog/1.webp",
    mdPath: "/articles/git-pull-vs-fetch-na-praktike.md",
  },
  {
    id: "3",
    slug: "react-memo-kogda-i-zachem",
    title: "React.memo: когда он реально нужен (и когда мешает)",
    description:
      "Понятно и по делу: как работают ре-рендеры, где React.memo помогает, и почему иногда лучше начать с архитектуры.",
    date: "2025-12-16",
    tags: ["React", "Практика"],
    author: { name: "n1ckwhite", github: "n1ckwhite" },
    viewsCount: 1540,
    starsCount: 61,
    commentsCount: 9,
    readingTime: "6 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/react-memo-kogda-i-zachem.md",
  },
  {
    id: "4",
    slug: "typescript-generics-prosto",
    title: "TypeScript Generics — просто и по делу",
    description: "Как читать и писать дженерики, чтобы типы помогали, а не мешали.",
    date: "2025-12-15",
    tags: ["TypeScript", "Практика"],
    author: { name: "aiffadev", github: "aiffadev" },
    viewsCount: 2120,
    starsCount: 73,
    commentsCount: 14,
    readingTime: "8 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/typescript-generics-prosto.md",
  },
  {
    id: "5",
    slug: "nextjs-metadata-seo",
    title: "Next.js Metadata: как сделать SEO без боли",
    description: "Что реально важно: title/description, canonical, openGraph и структурированные данные.",
    date: "2025-12-14",
    tags: ["Next.js", "SEO"],
    author: { name: "n1ckwhite", github: "n1ckwhite" },
    viewsCount: 1870,
    starsCount: 64,
    commentsCount: 11,
    readingTime: "7 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/nextjs-metadata-seo.md",
  },
  {
    id: "6",
    slug: "chakra-ui-patterny-kartochek",
    title: "Chakra UI: паттерны карточек и сеток для продакшена",
    description: "Как собирать UI из простых блоков: сетки, карточки, hover и типографика.",
    date: "2025-12-13",
    tags: ["Chakra UI", "UI"],
    author: { name: "aiffadev", github: "aiffadev" },
    viewsCount: 1430,
    starsCount: 41,
    commentsCount: 6,
    readingTime: "6 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/chakra-ui-patterny-kartochek.md",
  },
  {
    id: "7",
    slug: "a11y-focus-visible",
    title: "A11y: focus-visible без боли",
    description: "Как сделать фокус заметным и не раздражающим: практические советы и примеры.",
    date: "2025-12-12",
    tags: ["Accessibility", "Практика"],
    author: { name: "n1ckwhite", github: "n1ckwhite" },
    viewsCount: 980,
    starsCount: 29,
    commentsCount: 4,
    readingTime: "5 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/a11y-focus-visible.md",
  },
  {
    id: "8",
    slug: "nodejs-event-loop-na-palcah",
    title: "Node.js event loop — на пальцах",
    description: "Очереди, microtasks и почему setTimeout(0) не всегда \"сразу\".",
    date: "2025-12-11",
    tags: ["Node.js", "База"],
    author: { name: "aiffadev", github: "aiffadev" },
    viewsCount: 1650,
    starsCount: 57,
    commentsCount: 8,
    readingTime: "7 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/nodejs-event-loop-na-palcah.md",
  },
  {
    id: "9",
    slug: "css-grid-shpargalka",
    title: "CSS Grid — короткая шпаргалка",
    description: "Самые нужные свойства и 3 шаблона сетки для реальных экранов.",
    date: "2025-12-09",
    tags: ["CSS", "Frontend"],
    author: { name: "n1ckwhite", github: "n1ckwhite" },
    viewsCount: 1240,
    starsCount: 38,
    commentsCount: 5,
    readingTime: "5 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/css-grid-shpargalka.md",
  },
  {
    id: "10",
    slug: "git-rebase-bez-paniki",
    title: "Git rebase без паники",
    description: "Когда rebase уместен, как чинить конфликты и не потерять историю.",
    date: "2025-12-08",
    tags: ["Git", "Практика"],
    author: { name: "aiffadev", github: "aiffadev" },
    viewsCount: 1920,
    starsCount: 70,
    commentsCount: 13,
    readingTime: "9 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/git-rebase-bez-paniki.md",
  },
  {
    id: "11",
    slug: "testy-react-minimum",
    title: "Тесты в React: минимальный набор, который реально нужен",
    description: "Что тестировать в первую очередь и как не превратить тесты в ад.",
    date: "2025-12-07",
    tags: ["React", "Testing"],
    author: { name: "n1ckwhite", github: "n1ckwhite" },
    viewsCount: 1100,
    starsCount: 33,
    commentsCount: 3,
    readingTime: "6 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/testy-react-minimum.md",
  },
  {
    id: "12",
    slug: "docker-dev-setup",
    title: "Docker для разработки: быстрый сетап без лишнего",
    description: "Как сделать окружение воспроизводимым и не убить скорость разработки.",
    date: "2025-12-05",
    tags: ["DevOps", "Docker"],
    author: { name: "aiffadev", github: "aiffadev" },
    viewsCount: 890,
    starsCount: 21,
    commentsCount: 2,
    readingTime: "5 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/docker-dev-setup.md",
  },
  {
    id: "13",
    slug: "perf-react-render-loop",
    title: "Почему компонент рендерится 100 раз: чек-лист",
    description: "Типовые причины рендер-лупов и как быстро локализовать источник.",
    date: "2025-12-04",
    tags: ["React", "Performance"],
    author: { name: "n1ckwhite", github: "n1ckwhite" },
    viewsCount: 1760,
    starsCount: 58,
    commentsCount: 10,
    readingTime: "7 мин",
    coverImage: "/images/blog/1.webp",
    mdPath: "/articles/perf-react-render-loop.md",
  },
];

export const getBlogArticleBySlug = (slug: string): BlogArticleMeta | undefined => {
  return blogArticles.find((a) => a.slug === slug);
};

export const getBlogArticleById = (id: string): BlogArticleMeta | undefined => {
  const safeId = String(id ?? "").trim();
  if (!safeId) return undefined;
  return blogArticles.find((a) => String(a.id) === safeId);
};


